apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-service
  labels:
    app: currency-conversion-service
spec:
  selector:
    app: currency-conversion-service
  type: LoadBalancer
  ports:
    - port: 8100
      targetPort: 8100
      nodePort: 30081
