apiVersion: v1
kind: Service
metadata:
  name: currency-exchange-service
  labels:
    app: currency-exchange-service
spec:
  selector:
    app: currency-exchange-service
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
