apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: currency-exchange-service
spec:
  selector:
    matchLabels:
      app: currency-exchange-service
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: currency-exchange-service
    spec:
      containers:
      - name: currency-exchange-service
        image: currency-exchange-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
